In [116]:
my_list=[1,2,3]

In [117]:
import numpy as np

In [118]:
arr = np.array(my_list)

In [119]:
arr

array([1, 2, 3])

In [120]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [121]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [124]:
np.arange(0,5,2)

array([0, 2, 4])

In [125]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [126]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [127]:
np.linspace(0,5,100) 

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [128]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [129]:
np.random.rand(9)

array([0.86152055, 0.16587423, 0.94048424, 0.56355111, 0.08383244,
       0.49940356, 0.62374026, 0.69186547, 0.90176487])

In [130]:
np.random.rand(3,5)

array([[0.26641125, 0.36106484, 0.18061818, 0.10233965, 0.66739595],
       [0.2252667 , 0.7352666 , 0.71140121, 0.17595773, 0.49484589],
       [0.30000268, 0.51616442, 0.05157743, 0.53549821, 0.16944726]])

In [131]:
np.random.randn(4)

array([ 0.9017818 ,  1.08108578, -2.14267667,  1.89030787])

In [132]:
np.random.randn(2,2)

array([[ 1.18370097, -1.19214551],
       [ 0.59791705,  0.07857642]])

In [133]:
np.random.randint(1,100)

25

In [134]:
np.random.randint(1,100,10)

array([ 1, 12, 37, 12, 97, 58, 78,  2,  3, 15])

In [135]:
arr = np.arange(0,100)

In [136]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [137]:
ranarr = np.random.randint(0,50,12)

In [138]:
ranarr

array([ 4, 32, 31, 46, 29, 44, 42, 14, 36, 23, 22, 45])

In [139]:
arr.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [140]:
ranarr.max()

46

In [141]:
ranarr.min()

4

In [142]:
ranarr.argmax()

3

In [143]:
ranarr.argmin()

0

In [144]:
# numpy indexing and selection

In [145]:
import numpy as np

In [146]:
arr = np.arange(0,11)

In [147]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [148]:
arr[6]

6

In [149]:
arr[3:6]

array([3, 4, 5])

In [150]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [151]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [152]:
arr[0:5]= 100

In [153]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [154]:
arr=np.arange(0,11)

In [155]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [156]:
slice_of_arr= arr[0:6]

In [157]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [158]:
slice_of_arr[:] = 99

In [159]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [160]:
#indexing a matrix(2d array)

In [161]:
import numpy as np

In [162]:
arr_2d=np.array([[(5,10,15),(20,25,30),(35,40,45)]])

In [163]:
arr_2d

array([[[ 5, 10, 15],
        [20, 25, 30],
        [35, 40, 45]]])

In [164]:
arr_2d[0][0]

array([ 5, 10, 15])

In [165]:
arr_2d[2:1]

array([], shape=(0, 3, 3), dtype=int32)

In [166]:
#grabing certain matrices from a matrix

In [167]:
arr_2d[:2,1:]

array([[[20, 25, 30],
        [35, 40, 45]]])

In [168]:
arr_2d[:2]

array([[[ 5, 10, 15],
        [20, 25, 30],
        [35, 40, 45]]])

In [169]:
#conditional selection

In [170]:
arr = np.arange(1,11)

In [171]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [172]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [173]:
bool_arr = arr > 5

In [174]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [175]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [176]:
#only return instances when the boolean array is true

In [177]:
arr[arr>5] #second method

array([ 6,  7,  8,  9, 10])

In [178]:
arr[arr<3]

array([1, 2])

In [179]:
# numpy operations

In [180]:
import numpy as np

In [181]:
arr = np.arange(0,11)

In [182]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [183]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [185]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [186]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [187]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [188]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [189]:
arr - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [190]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [191]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [192]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [193]:
#panda series 

In [194]:
import numpy as np

In [195]:
import pandas as pd

In [196]:
labels = ['a','b','c']
my_data = [10, 20, 30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30 }

In [197]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [198]:
pd.Series(data = my_data, index = labels)

a    10
b    20
c    30
dtype: int64

In [199]:
from numpy.random import randn

In [200]:
ser1 = pd.Series([1,2,3,4],['USA','Germany','USSR','Japan'])

In [201]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [202]:
ser2 = pd.Series([1,2,5,4],['USA','Germany','itally','Japan'])

In [203]:
ser2

USA        1
Germany    2
itally     5
Japan      4
dtype: int64

In [204]:
ser1['USA']

1

In [205]:
ser1 + ser2

Germany    4.0
Japan      8.0
USA        2.0
USSR       NaN
itally     NaN
dtype: float64

In [206]:
#data frames

In [207]:
import numpy as pd

In [208]:
import pandas as pd

In [209]:
from numpy.random import randn

In [210]:
np.random.seed(101)

In [211]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [212]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [213]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [214]:
type(df['W'])

pandas.core.series.Series

In [215]:
type(df)

pandas.core.frame.DataFrame

In [216]:
df['Z']

A    0.503826
B    0.605965
C   -0.589001
D    0.955057
E    0.683509
Name: Z, dtype: float64

In [217]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [218]:
df['new'] = df['W'] + df['Y']

In [219]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [220]:
df.drop('new',axis=1, inplace = True)

In [221]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [222]:
df.shape

(5, 4)

In [223]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [224]:
df.loc['B','Y']

-0.8480769834036315

In [225]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [226]:
#conditional selection of data frames

In [227]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [228]:
booldf = df > 0

In [229]:
booldf

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [230]:
df[booldf]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [231]:
df['W']>0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [232]:
df[df['Z']< 0]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [233]:
resultdf = df[df['W']>0]

In [234]:
resultdf

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [235]:
#we can go ahad to drive result of of this example

In [236]:
resultdf['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [237]:
df[df['W']>0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [238]:
 df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509